### ISSUE TITLE
Objecting to stale issue bots

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/governance#16]
I don't really do much to help maintain the contrib libraries so maybe this isn't really my place to say, but I'm really not a fan of bots which comment on and then close stale issues. If someone went to the effort of writing up an issue to help improve a library, I think we ought to at least have a person give a description of why we aren't going to act on it if we close it, rather than having a bot do it for us. I think having your issue closed by a bot is likely to be perceived as unfriendly by most potential contributors. For example, see this Twitter thread: https://twitter.com/sindresorhus/status/1082145283285250048. Additionally, I think "no action for X amount of time" is generally not a very reliable indicator of issues which should be closed; I'm sure there are tons of issues which haven't had any comments for months across the purescript and purescript-contrib orgs, but which are still legitimate issues which should be addressed if someone has the time or inclination to work on a particular library. I think stale issue bots make sense for projects which are drowning in issues, but I think the majority of libraries in core or contrib probably have under 20 open issues. Are these bots a net good?

**Comment by thomashoneyman** [comment]
> If someone went to the effort of writing up an issue to help improve a library, I think we ought to at least have a person give a description of why we aren't going to act on it if we close it, rather than having a bot do it for us.

This is a good point. The current state of affairs is only marginally better (often _years_ without a response), but I agree there's certain coldness to a bot response that goes against a principle of this organization -- to be empathetic.

> Additionally, I think "no action for X amount of time" is generally not a very reliable indicator of issues which should be closed; I'm sure there are tons of issues which haven't had any comments for months across the purescript and purescript-contrib orgs, but which are still legitimate issues which should be addressed if someone has the time or inclination to work on a particular library.

I agree. We have some definite triaging to do, and time is not necessarily a good indicator of which issues should go.

> Are these bots a net good?

On reflection, probably not.

However, for context: I had two major motivations in adding the stale issue bot.

First, the bot serves as a ping to consider an issue that is becoming stale / neglected. That doesn't necessarily mean that it should be closed, but it puts it back in maintainer inboxes and reminds the person who opened the issue or PR about it. Sometimes the issue or PR should just be closed, but I was anticipating this would help us follow up on issues and pull requests that would otherwise be forgotten entirely.

Second, the majority of libraries in this organization are maintained by the same couple people, and while a small number of issues per library is not much, once you spread that across 50 projects they add up.

That said, this is probably the wrong solution to the problem of not having enough people interacting with these issues and pull requests across the organization.

**Comment by hdgarrood** [comment]
For a while, I have wanted to have a tool which can show me issues across all of the repositories in a given organization at once, together with all of the usual sorting and filtering abilities (open, closed, last updated, etc). I think that might help solve this issue, at least partially. I would guess there's a good chance something like that already exists? I did have a brief look for something that can do this a little while ago, but didn't find anything.

**Comment by garyb** [comment]
Is that different than the view that something like https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Apurescript provides?

**Comment by hdgarrood** [comment]
Oh my god, how did I not know about that

**Comment by garyb** [comment]
:smile:

Someone pointed it out to me originally too. It's strange how something that is part of the main nav of the site goes so easily unnoticed. A bit of a design failure, I'd say.

**Comment by JordanMartinez** [comment]
@thomashoneyman I'm in favor of removing the "bot closes an issue" idea, too. It felt cold to me when I saw it happen originally.

Could we also save Gary's search above but for `purescript-contrib`? It might be helpful for ourselves and others who want to know how to contribute. I think the link could go in this repo's readme or something for those who are looking to help.
