### ISSUE TITLE
Absorb archived libraries into PureScript contrib

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/governance#38]
Should we migrate more archived libraries into this contrib org so we can ensure they're kept up to date and available in the latest package sets?
One candidate is the `event` library (https://github.com/paf31/purescript-event/pull/7).

**Comment by JordanMartinez** [comment]
I think one reason why that wasn't done earlier was because it wasn't clear who would maintain it. That's why I responded [to a similar question](https://github.com/purescript/package-sets/issues/856#issuecomment-797023435) in the way that I did.

Would you be willing to maintain `event`?

**Comment by thomashoneyman** [comment]
The halogen-subscriptions library absorbed the relevant parts of event for Halogen applications, though its useful beyond just Halogen. Otherwise, without a committed maintainer in contrib I would rather not absorb libraries. We already have a problem with too many libraries and too few knowledgeable maintainers for them.

**Comment by garyb** [comment]
Also, Phil doesn't want to transfer his archived libraries. He feels like there's little evidence of his public PS projects anymore so wants to keep the few he has left under his name.

**Comment by thomashoneyman** [comment]
Yes, that as well. Though I’m including forking to contrib as something I’d only want to do with a dedicated maintainer.

**Comment by milesfrain** [comment]
I guess it's straightforward enough to just fork an archived library as an individual and republish.
