### ISSUE TITLE
All members should be Public

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/governance#41]
Before I became a member, I though there were only like nine people in the __purescript-contrib__ organization, because most of the members are Private.

https://github.com/orgs/purescript-contrib/people

I think all members should change their visibility to Public.

**Comment by thomashoneyman** [comment]
If folks in the organization chime in here and agree we should all be public then we could make a guideline suggesting it, but I’m hesitant to say that you can’t be in the organization unless you’re public.

This can only be enforced socially (ie. there’s no way to disallow private membership afaik), and I think we’d need the benefits of everyone being public to outweigh the social cost of making sure folks are public members even if they don’t want to be.

**Comment by JordanMartinez** [comment]
I think I'm against this for the reasons Thomas stated above. Sometimes, being public means people might think they can `@` you whenever they have a problem because you technically could help address whatever issue they have (e.g. creating a new release).
Also, just because someone is a part of this group doesn't mean they are actively involved all the time. By being public, it could miscommunicate that, too.

I do think a few members should be public so someone can respond to people outside the group, but I don't think everyone should be public.

**Comment by jamesdbrock** [comment]
~I think all~ *This is a reminder that* members should change their visibility to Public *, assuming they're Private because that’s the Github default and they haven't bothered to change it.*

**Comment by JordanMartinez** [comment]
I definitely fell into that group of not knowing I needed to change it.

**Comment by f-f** [comment]
I semi-consciously chose not to set it as Public, because I am part of so many orgs and I started curating the ones that are shown in my profile.
